### ISSUE TITLE
Cannot create rancher2_app with catalog scoped at cluster or project level

### ISSUE THREAD

**Issue by donovanmuller** [rancher/terraform-provider-rancher2#146]
If I have a custom catalog scoped at Global level. API view below:

```json
{
  "actions":{
    "refresh":"https://xxx/v3/catalogs/test-cat?action=refresh"
  },
  "annotations":{

  },
  "baseType":"catalog",
  "branch":"master",
  "commit":"020a188dbe1fb253863715b69fef1688bedd6ce0",
  "conditions":[
...
  ],
  "created":"2019-10-01T14:07:56Z",
  "createdTS":1569938876000,
  "creatorId":"user-fhqws",
  "description":"",
  "id":"test-cat",
  "kind":"helm",
  "labels":{
    "cattle.io/creator":"norman"
  },
  "links":{
    "exportYaml":"https://xxx/v3/catalogs/test-cat/exportyaml",
    "remove":"https://xxx/v3/catalogs/test-cat",
    "self":"https://xxx/v3/catalogs/test-cat",
    "templates":"https://xxx/v3/templates?catalogId=test-cat",
    "update":"https://xxx/v3/catalogs/test-cat"
  },
  "name":"test-cat",
  "state":"active",
  "transitioning":"no",
  "transitioningMessage":"",
  "type":"catalog",
  "url":"https://github.com/xxx/charts.git",
  "username":"xxx",
  "uuid":"de130113-e454-11e9-b2fa-42010a000011"
}
```

then the following Terraform successfully creates an application:

```terraform
resource "rancher2_app" "cat-test" {
    catalog_name = "test-cat"
    name = "cat-test"
    project_id = data.rancher2_project.test-project.id
    template_name = "test-app"
    template_version = "0.1.0"
    target_namespace = "cat-test"
}
```

However, if I change the scope of the Catalog to either Cluster or Project, then I cannot create an application. Following the naming convention for [`catalog_name`](https://www.terraform.io/docs/providers/rancher2/r/app.html#catalog_name) mentioned in the docs for cluster or project scoped catalogs:

```terraform
resource "rancher2_app" "cat-test" {
    catalog_name = "c-2jsz5:test-cat"
    // -- or --
    //catalog_name = "p-9skfn:test-cat"
    name = "cat-test"
    project_id = data.rancher2_project.test-project.id
    template_name = "test-app"
    template_version = "0.1.0"
    target_namespace = "cat-test"
}
```

and I get the following error when running `terraform apply`:

```console
rancher2_app.cat-test: Creating...

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogtemplateversions.management.cattle.io "c-2jsz5:test-cat-test-app-0.1.0" not found] from [https://xxx/v3/project/c-2jsz5:p-9skfn/apps]

  on main.tf line 42, in resource "rancher2_app" "cat-test":
  42: resource "rancher2_app" "cat-test" {
```

and 

```console
rancher2_app.cat-test: Creating...

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogtemplateversions.management.cattle.io "p-9skfn:test-cat-test-app-0.1.0" not found] from [https://xxx/v3/project/c-2jsz5:p-9skfn/apps]

  on main.tf line 42, in resource "rancher2_app" "cat-test":
  42: resource "rancher2_app" "cat-test" {
```

respectively.

For reference the API view of `https://xxx/v3/project/c-2jsz5:p-9skfn/apps` is:

```json
{
  "type":"collection",
  "links":{
    "self":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps"
  },
  "createTypes":{
    "app":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps"
  },
  "actions":{

  },
  "pagination":{
    "limit":1000,
    "total":0
  },
  "sort":{
    "order":"asc",
    "reverse":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?order=desc",
    "links":{
      "description":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=description",
      "externalId":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=externalId",
      "lastAppliedTemplate":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=lastAppliedTemplate",
      "notes":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=notes",
      "state":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=state",
      "targetNamespace":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=targetNamespace",
      "transitioning":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=transitioning",
      "transitioningMessage":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=transitioningMessage",
      "uuid":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=uuid",
      "valuesYaml":"https://xxx/v3/project/c-2jsz5:p-9skfn/apps?sort=valuesYaml"
    }
  },
  "filters":{
    "appRevisionId":null,
    "created":null,
    "creatorId":null,
    "description":null,
    "externalId":null,
    "lastAppliedTemplate":null,
    "multiClusterAppId":null,
    "name":null,
    "namespaceId":null,
    "notes":null,
    "projectId":null,
    "prune":null,
    "removed":null,
    "state":null,
    "targetNamespace":null,
    "transitioning":null,
    "transitioningMessage":null,
    "uuid":null,
    "valuesYaml":null
  },
  "resourceType":"app",
  "data":[

  ]
}
```

**Comment by rawmind0** [comment]
Hi @donovanmuller, yeah this is a reported bug and was addressed on PR #132.

We expect to cut a new release including the patch at the end of this week. If you are in hurry, you could build provider from master branch.

**Comment by donovanmuller** [comment]
@rawmind0 Ok awesome, I only wished I had seen the PR before typing this issue out 😄  I'll do a local build cause I would rather not have to resort to using a Global catalog. 👍

**Comment by donovanmuller** [comment]
Ok, built and tested locally. It's working now 👍

**Comment by msnelling** [comment]
I'm still seeing this issue with version 1.8.3 of the provider. Is this a regression?

**Comment by rawmind0** [comment]
I don't think so. Feature should work fine. Could you provide your ft file??

**Comment by msnelling** [comment]
Here's a sample `.tf` file.
```
data rancher2_cluster test {
  name = "k8s"
}

data rancher2_project system {
  cluster_id = data.rancher2_cluster.test.id
  name       = "System"
}

resource rancher2_catalog jetstack_global {
  name       = "jetstack-test"
  url        = "https://charts.jetstack.io"
  scope      = "global"
  version    = "helm_v2"
  refresh    = true
  cluster_id = data.rancher2_cluster.test.id
}

resource rancher2_catalog jetstack_cluster {
  name       = "jetstack-test"
  url        = "https://charts.jetstack.io"
  scope      = "cluster"
  version    = "helm_v2"
  refresh    = true
  cluster_id = data.rancher2_cluster.test.id
}

resource rancher2_app cert_manager {
  name             = "cert-manager"
  template_name    = "cert-manager"
  #catalog_name     = "${data.rancher2_cluster.test.id}:jetstack-test"
  catalog_name     = "jetstack-test"
  project_id       = data.rancher2_project.system.id
  target_namespace = "cert-manager"

  answers = {
    "image.pullPolicy"            = "Always"
    "webhook.image.pullPolicy"    = "Always"
    "cainjector.image.pullPolicy" = "Always"
    "extraArgs"                   = "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"
  }
}
```

**Comment by rawmind0** [comment]
If you want to use scoped catalogs for an app, the catalog_name should be provided in a proper format, https://www.terraform.io/docs/providers/rancher2/r/app.html#catalog_name

Referencing your example, should work with 

```
  catalog_name     = rancher2_catalog jetstack_cluster.id
# OR
  catalog_name     = "${rancher2_catalog jetstack_cluster.cluster_id}:${rancher2_catalog jetstack_cluster.name}"
```

**Comment by msnelling** [comment]
Thanks @rawmind0, I just tried both of those with the above `.tf` file and they both give the error
```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogtemplateversions.management.cattle.io "jetstack-test-cert-manager-0.15.0" not found] from [https://rancher.xmple.io/v3/project/c-wghjf:p-c2hdq/apps]
```
This is the plan that it tries to execute...
```
data.terraform_remote_state.rancher: Refreshing state...
data.rancher2_cluster.test: Refreshing state...
rancher2_catalog.jetstack_global: Refreshing state... [id=jetstack-test]
data.rancher2_project.system: Refreshing state...
rancher2_catalog.jetstack_cluster: Refreshing state... [id=c-wghjf:jetstack-test]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # rancher2_app.cert_manager will be created
  + resource "rancher2_app" "cert_manager" {
      + annotations      = (known after apply)
      + answers          = {
          + "cainjector.image.pullPolicy" = "Always"
          + "extraArgs"                   = "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"
          + "image.pullPolicy"            = "Always"
          + "webhook.image.pullPolicy"    = "Always"
        }
      + catalog_name     = "c-wghjf:jetstack-test"
      + description      = (known after apply)
      + external_id      = (known after apply)
      + force_upgrade    = false
      + id               = (known after apply)
      + labels           = (known after apply)
      + name             = "cert-manager"
      + project_id       = "c-wghjf:p-c2hdq"
      + revision_id      = (known after apply)
      + target_namespace = "cert-manager"
      + template_name    = "cert-manager"
      + template_version = (known after apply)
    }
```

**Comment by rawmind0** [comment]
Try to specify the template version. There is a bug with version containing initial `v` that will be addressed with PR #336 

`template_version = "v0.15.0"`

**Comment by msnelling** [comment]
@rawmind0 that did the trick thanks.
