### ISSUE TITLE
Syntax of catalog_name of rancher2_app resource is different between rancher cluster and managed cluster

### ISSUE THREAD

**Issue by caiconkhicon** [rancher/terraform-provider-rancher2#334]
I want to create a cluster scoped catalog and create an application from it. Follow the documentation here: https://www.terraform.io/docs/providers/rancher2/r/app.html#argument-reference, I set the argument `catalog_name` for the resource `rancher2_app`. 
It worked well for the managed cluster, but it fails for the Rancher cluster. In this case, I set: 

`
catalog_name     = "local:elastic"
`

It failed with the error:

`
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=catalogtemplateversions.management.cattle.io "local:elastic-elasticsearch-7.6.2" not found, baseType=error, code=ServerError] from [https://my-rancher.io/v3/project/local:p-rcqlh/apps]
`

After struggling for some time, I found the fix, which was to replace the `:` with a `/`, so:

`
catalog_name     = "local/elastic"
`

My question is why is it inconsistent like this? It breaks my terraform automation, because I set

`
catalog_name     = rancher2_catalog.elastic.id
`

and the `id` attribute of `rancher2_catalog` uses `:` (i.e. "local:elastic")

**Comment by rawmind0** [comment]
The syntax shouldn't be different, this is correct `catalog_name = "local:elastic"`, but not working due to a bug. Thanks for reporting.

The issue is just occurring with `local` cluster scope catalogs. It should be addressed with PR #336

**Comment by caiconkhicon** [comment]
Thanks a lot for your quick reply. I will try it soon.

**Comment by caiconkhicon** [comment]
@rawmind0 : Can you please check again. I tried and it failed with the error:

`
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=catalogtemplateversions.management.cattle.io "elastic-kibana-7.6.2" not found, baseType=error, code=ServerError] from [https://my-rancher.io/v3/project/local:p-rcqlh/apps]
`

Note that the search item is `elastic-kibana-7.6.2`, while the correct one should be `local-elastic-kibana-7.6.2`. Thus I guess somehow your change forget to add the cluster id to the searching query.

**Comment by rawmind0** [comment]
@caiconkhicon have you build the provider from the PR??  Could you please rebase PR, build and test with it. For me is working fine

**Comment by caiconkhicon** [comment]
@rawmind0: I tried again, still the same result:

1. Completely remove the old local repo
2. `git clone https://github.com/rawmind0/terraform-provider-rancher2.git`
3. `git checkout app` (check again, your 2 new commits are there)
4. Build and copy the binare into ~/.terraform.d/plugins
5. Remove .terraform dir and rerun `terraform init`
6. The output with the error:

```
Terraform will perform the following actions:

  # module.logging.rancher2_app.kibana will be created
  + resource "rancher2_app" "kibana" {
      + annotations      = (known after apply)
      + catalog_name     = "local:elastic"
      + description      = "Kibana is an open source data visualization dashboard for Elasticsearch."
      + external_id      = (known after apply)
      + force_upgrade    = false
      + id               = (known after apply)
      + labels           = (known after apply)
      + name             = "kibana"
      + project_id       = "local:p-rcqlh"
      + revision_id      = (known after apply)
      + target_namespace = "logging"
      + template_name    = "kibana"
      + template_version = "7.6.2"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.logging.rancher2_app.kibana: Creating...

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=ServerError, message=catalogtemplateversions.management.cattle.io "elastic-kibana-7.6.2" not found, baseType=error] from [https://my-rancher.io/v3/project/local:p-rcqlh/apps]
```

**Comment by rawmind0** [comment]
Weird, working fine for me...

```
terraform apply
rancher2_catalog.elastic: Refreshing state... [id=local:elastic]
rancher2_catalog.jetstack_cluster: Refreshing state... [id=local:jetstack-test]
rancher2_namespace.foo: Refreshing state... [id=foo]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # rancher2_app.kibana will be created
  + resource "rancher2_app" "kibana" {
      + annotations      = (known after apply)
      + catalog_name     = "local:elastic"
      + description      = (known after apply)
      + external_id      = (known after apply)
      + force_upgrade    = false
      + id               = (known after apply)
      + labels           = (known after apply)
      + name             = "kibana"
      + project_id       = "local:p-tqz59"
      + revision_id      = (known after apply)
      + target_namespace = "foo"
      + template_name    = "kibana"
      + template_version = "7.6.2"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rancher2_app.kibana: Creating...
rancher2_app.kibana: Still creating... [10s elapsed]
rancher2_app.kibana: Creation complete after 15s [id="p-tqz59:kibana"]
```

**Comment by caiconkhicon** [comment]
@rawmind0 : I tried on 2 machines, both had the same result. The only issue I can think of is the Golang version, maybe?
Both machines I tried are MacOS. The Golang version is:

`go version go1.14 darwin/amd64` (one has 1.14.2)

In the README it says using go1.12.

**Comment by Jasper-Ben** [comment]
same issue here. PR also doesn't seem to fix it.
`go version go1.14.2 linux/amd64`

```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=catalogtemplateversions.management.cattle.io "helm-stable-jenkins-1.19.0" not found, baseType=error, code=ServerError] from [https://localhost/v3/project/c-dj2jn:p-qxgtw/apps]

  on main.tf line 52, in resource "rancher2_app" "jenkins":
  52: resource "rancher2_app" "jenkins" {
```
```
...

resource "rancher2_catalog" "helmStable" {
    provider    = rancher2.admin
    name        = "helm-stable"
    url         = "https://kubernetes-charts.storage.googleapis.com"
    kind        = "helm"
    version     = "helm_v3"
    scope       = "project"
    project_id  = rancher2_project.jenkins.id
    depends_on  = [
        data.rancher2_cluster.cluster,
        rancher2_project.jenkins,
    ]
}
resource "rancher2_app" "jenkins" {
    provider            = rancher2.admin
    catalog_name        = rancher2_catalog.helmStable.id
    name                = "jenkins"
    project_id          = rancher2_project.jenkins.id
    template_name       = "jenkins"
    template_version    = "1.19.0"
    target_namespace    = rancher2_namespace.jenkins.name
    values_yaml         = filebase64("${path.module}/helm_values.yml")
    depends_on = [
        data.rancher2_cluster.cluster,
        rancher2_catalog.helmStable,
        rancher2_project.jenkins,
        rancher2_namespace.jenkins,
    ]
}
```

**Comment by rawmind0** [comment]
@Jasper-Ben  working for me with the PR applied, seems that fix it

```
terraform apply
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # rancher2_namespace.jenkins will be created
  + resource "rancher2_namespace" "jenkins" {
      + annotations      = (known after apply)
      + id               = (known after apply)
      + labels           = (known after apply)
      + name             = "jenkins"
      + project_id       = "local:p-qrs4z"
      + wait_for_cluster = false
    }

  # rancher2_catalog.helmStable will be created
  + resource "rancher2_catalog" "helmStable" {
      + annotations = (known after apply)
      + branch      = "master"
      + id          = (known after apply)
      + kind        = "helm"
      + labels      = (known after apply)
      + name        = "helm-stable"
      + project_id  = "local:p-qrs4z"
      + refresh     = false
      + scope       = "project"
      + url         = "https://kubernetes-charts.storage.googleapis.com"
      + version     = "helm_v3"
    }

  # rancher2_app.jenkins will be created
  + resource "rancher2_app" "jenkins" {
      + annotations      = (known after apply)
      + catalog_name     = "p-qrs4z:helm-stable"
      + description      = (known after apply)
      + external_id      = (known after apply)
      + force_upgrade    = false
      + id               = (known after apply)
      + labels           = (known after apply)
      + name             = "jenkins"
      + project_id       = "local:p-qrs4z"
      + revision_id      = (known after apply)
      + target_namespace = "jenkins"
      + template_name    = "jenkins"
      + template_version = "1.19.0"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rancher2_catalog.helmStable: Creating...
rancher2_namespace.jenkins: Creating...
rancher2_catalog.helmStable: Creation complete after 1s [id=p-qrs4z:helm-stable]
rancher2_namespace.jenkins: Creation complete after 1s [id=jenkins]
rancher2_app.jenkins: Creating...
rancher2_app.jenkins: Creation complete after 5s [id=p-qrs4z:jenkins]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by Jasper-Ben** [comment]
I am not sure why, but for me it is hit and miss... I had to run `terraform apply` three times (without changing anything to the config) for it to work.

```
jasper@arch-pc terraform]$ terraform apply                                                                                                                                                                                                   
data.rancher2_cluster.cluster: Refreshing state...                                                                                                                                                                                            
rancher2_project.jenkins: Refreshing state... [id=c-dj2jn:p-7cb6j]                                                                                                                                                                            
rancher2_catalog.helmStable: Refreshing state... [id=p-7cb6j:helm-stable]                                                                                                                                                                     
rancher2_namespace.jenkins: Refreshing state... [id=jenkins]                                                                                                                                                                                  
                                                                                                                                                                                                                                              
An execution plan has been generated and is shown below.                                                                                                                                                                                      
Resource actions are indicated with the following symbols:                                                                                                                                                                                    
  + create                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                              
Terraform will perform the following actions:                                                                                                                                                                                                 
                                                                                                                                                                                                                                              
  # rancher2_app.jenkins will be created                                                                                                                                                                                                      
  + resource "rancher2_app" "jenkins" {                                                                                                                                                                                                       
      + annotations      = (known after apply)                                                                                                                                                                                                
      + catalog_name     = "p-7cb6j:helm-stable"                                                                                                                                                                                              
      + description      = (known after apply)                                                                                                                                                                                                
      + external_id      = (known after apply)                                                                                                                                                                                                
      + force_upgrade    = false                                                                                                                                                                                                              
      + id               = (known after apply)                                                                                                                                                                                                
      + labels           = (known after apply)                                                                                                                                                                                                
      + name             = "jenkins"                                                                                                                                                                                                          
      + project_id       = "c-dj2jn:p-7cb6j"                                                                                                                                                                                                  
      + revision_id      = (known after apply)                                                                                                                                                                                                
      + target_namespace = "jenkins"                                                                                                                                                                                                          
      + template_name    = "jenkins"                                                                                                                                                                                                          
      + template_version = "1.19.0"         

...

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogtemplateversions.management.cattle.io "helm-stable-jenkins-1.19.0" not found] from [https://localhost/v3/pro
ject/c-dj2jn:p-7cb6j/apps]                                                                                                                                                                                                                    

  on main.tf line 52, in resource "rancher2_app" "jenkins": 
  52: resource "rancher2_app" "jenkins" {

```

**Comment by Jasper-Ben** [comment]
and after destroying and recreating it again does not work. Have you tried creating it from scratch?

**Comment by Jasper-Ben** [comment]
terraform --version
Terraform v0.12.24
+ provider.rancher2 (unversioned)

Rancher | v2.4.3
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

Rancher and cluster are both run in a single docker container 

just to make sure, here is my entire main.tf:

https://paste.it-works-jbo.de/?32214f94a913f726#CG9GPGKWVwKnAqq9iP2BAScuP4stQaDnv84YFJr6GL1w

**Comment by Jasper-Ben** [comment]
it seems to me that the catalog is not yet ready when the app tries to start. So this might be an unrelated issue.

**Comment by caiconkhicon** [comment]
> it seems to me that the catalog is not yet ready when the app tries to start. So this might be an unrelated issue.

I know your issue. It is another one. It is the catalog taking time for refreshing.
I my case, it is the problem with the cluster scoped catalog.

**Comment by Jasper-Ben** [comment]
> > it seems to me that the catalog is not yet ready when the app tries to start. So this might be an unrelated issue.
> 
> I know your issue. It is another one. It is the catalog taking time for refreshing.
> I my case, it is the problem with the cluster scoped catalog.

Ahh I see. Thanks for the hint. I just saw your issue and assumed it was the same problem (didn't think to run apply twice in a row).

I just found https://github.com/terraform-providers/terraform-provider-rancher2/pull/203 and setting `refresh: true` did indeed fix the issue, though I don't understand why this isn't set to true by default...

Good luck with resolving the issue!

**Comment by caiconkhicon** [comment]
@rawmind0 : Hi, in fact it works. It was because of the newer version of Elasticsearch (which was released 2 days ago). They only keep the latest version, so the one I used above 7.6.2 was actually not available anymore. 
I still don't like that the error message doesn't show the cluster id (i.e. local) any more; but anyway, I think we can close this issue. 
Thanks a lot for your help.

PS: Is there any ETA for a new release?
