### ISSUE TITLE
rancher2_app_v2 fails waiting on system-default-registry setting propagation

### ISSUE THREAD

**Issue by mouellet** [rancher/terraform-provider-rancher2#627]
I'm using v1.13.0 to deploy an rke cluster with `rancher2_cluster`, making sure the cluster is active with the `rancher2_cluster_sync` resource and install gatekeeper using the `rancher2_app_v2` resource but I'm getting this error:

> Error: Bad response statusCode [404]. Status [404 Not Found]. Body: [code=NotFound, message=settings.management.cattle.io "system-default-registry" not found] from [https://<host_name>/k8s/clusters/<cluster_id>/v1/management.cattle.io.settings/system-default-registry]

It looks like the settings sync made by the `cattle-cluster-agent` workload can take up to 2 minutes. Is this expected?

Should the `rancher2_cluster_sync` resource have an option to wait on settings?

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/632 with a fix

**Comment by rawmind0** [comment]
Attached tfp custom binaries with patch applied to be tested, https://github.com/rancher/terraform-provider-rancher2/issues/648#issuecomment-832019144

**Comment by rawmind0** [comment]
The fix is available at tfp v1.14.0

**Comment by armsnyder** [comment]
@rawmind0 Hi Raul. Thanks for all the updates to this provider. ~Is using v1.14.0 supposed to resolve this, or are there some required attributes we need to set on the `rancher2_cluster_sync` resource?~

Also, the related upstream bug: https://github.com/rancher/rancher/issues/32642

~By the way my team is using imported clusters and still seeing this issue using v1.14.0.~

EDIT: Sorry, in our case it appears the original 404 did actually go away when we upgraded to v1.14.0. We specified the wrong catalog name and it was a different legitimate 404. Please disregard. 😄  The issue #662 is still valid however.

**Comment by rawmind0** [comment]
Hi @armsnyder , 
* about issue https://github.com/rancher/rancher/issues/32642 , global settings were synced on all k8s clusters API, but not anymore, so global settings as `system-default-registry`, has to be got from `local` cluster.
* about the issue #662 , retries seems to work fine, but not enough with default conf, agreed that it should be configurable. 

Working on a fix for both issues.
