### ISSUE TITLE
rancher2 bootstrap doesn't work anymore with rancher v2.6.0

### ISSUE THREAD

**Issue by batthebee** [rancher/terraform-provider-rancher2#738]
Here is my terraform script, which uses rancher v2.6.0 (latest).

```tf
terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "2.3.0"
    }
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.17.2"
    }
  }
}

provider "helm" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

provider "rancher2" {
  alias     = "bootstrap"
  api_url   = var.rancher_hostname != null ? "https://${var.rancher_hostname}" : "https://rancher.${var.lb_address}.nip.io"
  bootstrap = true
  insecure  = true
}

provider "rancher2" {
  alias     = "admin"
  api_url   = var.rancher_hostname != null ? "https://${var.rancher_hostname}" : "https://rancher.${var.lb_address}.nip.io"
  token_key = rancher2_bootstrap.setup_admin.token
  insecure  = true
}

resource "helm_release" "cert_manager" {
  name             = "cert-manager"
  namespace        = "cert-manager"
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = "1.5.3"

  wait             = true
  create_namespace = true
  force_update     = true
  replace          = true

  set {
    name  = "installCRDs"
    value = true
  }
}

resource "helm_release" "rancher" {
  name = "rancher"
  namespace = "cattle-system"
  chart = "rancher"
  repository = "https://releases.rancher.com/server-charts/latest"
  depends_on = [helm_release.cert_manager]

  wait             = true
  create_namespace = true
  force_update     = true
  replace          = true

  set {
    name  = "hostname"
    value = var.rancher_hostname != null ? var.rancher_hostname : "rancher.${var.lb_address}.nip.io"
  }

  set {
    name  = "ingress.tls.source"
    value = "letsEncrypt"
  }

  set {
    name  = "letsEncrypt.email"
    value = var.letsencrypt_issuer
  }
}

resource "rancher2_bootstrap" "setup_admin" {
  provider   = rancher2.bootstrap
  password   = var.rancher_admin_password
  telemetry  = true
  depends_on = [helm_release.rancher]
}
```

I get the following error:

```bash
│ Error: [ERROR] Timeout login with admin user: Doing  user logging: error Unauthorized
│ 
│   with module.rancher_init.rancher2_bootstrap.setup_admin,
│   on module-rancher-init/main.tf line 80, in resource "rancher2_bootstrap" "setup_admin":
│   80: resource "rancher2_bootstrap" "setup_admin" {
│ 
```
using rancher v2.5.9 from stable doesn't produce any error.

**Comment by mitchellmaler** [comment]
You have to set the bootstrapPassword helm value for rancher 2.6 to admin which is what the provider tries to login as. this wasn't required before when deploying.
--set bootstrapPassword=admin

**Comment by rawmind0** [comment]
You may have another option here, setting `--set bootstrapPassword=ANY_PASSWORD` and then configure the `rancher2_bootstrap.current_password=ANY_PASSWORD`, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap#current_password

**Comment by Playersux** [comment]
Sorry for the beginner question, But where do I use that --set command? I'm attempting to update an existing tf file and the documentation isn't really helping.

**Comment by batthebee** [comment]
Thanks, worked for me!

**Comment by rawmind0** [comment]
Glad to hear that @batthebee . Please, reopen the issue if needed.

**Comment by abhi1693** [comment]
@rawmind0 I'm on rancher 2.6.0 and have all the above changes in place. Today, I updated the admin password from rancher UI and terraform started throwing an `Unauthorized login` error even though I have passed the correct password. It seems like bootstrap only works until the password is not changed at all.
The error is while refreshing the state with the user for `rancher2_bootstrap.admin` when running a plan.

**Comment by rawmind0** [comment]
@abhi1693 , `rancher2_bootstrap` should work in the same way on Rancher 2.6.0. If you've updated your password from the ui and you are getting `Unauthorized login` from tf provider, then something is not updated properly on you tf file. Updating `password` and `current_paasword` to the current password should work fine, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap

**Comment by abhi1693** [comment]
@rawmind0 This was all working fine. I've been on v2.6.0 since the day it came out and did not face this issue until I updated the password on the UI for the default admin user.

```
provider "rancher2" {
  alias = "bootstrap"

  api_url   = "https://${var.server_url}"
  bootstrap = true
  insecure  = true
}

provider "rancher2" {
  alias = "admin"

  api_url   = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token
  insecure  = true
}

resource "rancher2_bootstrap" "admin" {
  provider   = rancher2.bootstrap
  depends_on = [null_resource.wait_for_rancher]

  password = var.admin_password
  current_password = var.admin_password
  telemetry        = false
  token_ttl        = 900
}
```

There hasn't been any change in our TF files at all. The only change is the password that was updated outside of terraform

**Comment by rawmind0** [comment]
> @rawmind0 This was all working fine. I've been on v2.6.0 since the day it came out and did not face this issue until I updated the password on the UI for the default admin user.

@abhi1693 , for sure your issue is coming from the updated password from the ui. 

> There hasn't been any change in our TF files at all. The only change is the password that was updated outside of terraform

As mentioned, you should update your tf file with the `password` and `current_password` arguments with the actual admin password. `current_password` argument was created for this concrete purpose, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap#current_password

**Comment by abhi1693** [comment]
@rawmind0 If you see my code above, I have already provided `password` and `current_password` the exact same variable.

I just reverted to the old password and the initial login issue got fixed without making any change to the TF files. Clearly, the issue is with the provider. But after doing so, the token generated from the provider when passed to other modules is now throwing `unauthorised error: must authenticate`.

I'm going to open a new issue and will tag you over there. I think there is a much bigger issue here than just changing password.

**Comment by rawmind0** [comment]
> @rawmind0 If you see my code above, I have already provided password and current_password the exact same variable.
>
> I just reverted to the old password and the initial login issue got fixed without making any change to the TF files. Clearly, the issue is with the provider. But after doing so, the token generated from the provider when passed to other modules is now throwing unauthorised error: must authenticate.

Yeah, but it's not clear what the value of this variable is.  If you reverted the old password (i guess from ui) and tfp is working fine again without making any change to the TF files, then may be the `var.admin_password` was not properly updated before, so not clear that the issue is on the provider. I don't know you tf modules structure but the token should also be updated properly once auth is working again. The bootstrap resource is using the token to auth first.

**Comment by jjhidalgar** [comment]
I have two issues with rancher v2.6.0. I am using both helm bootstrapPassword to a random value, and also current_password on terraform (and also password).

The issues are

1) Every now and then I get Unauthorized errors on terraform when applying. It fixes by just running apply again

2) Every time I run apply, I get this config skew:

    rancher2_bootstrap.admin will be updated in-place

And I did not change anything on the UI

**Comment by rawmind0** [comment]
> I have two issues with rancher v2.6.0. I am using both helm bootstrapPassword to a random value, and also current_password on terraform (and also password).
> 
> The issues are
> 
> 1. Every now and then I get Unauthorized errors on terraform when applying. It fixes by just running apply again
> 2. Every time I run apply, I get this config skew:
>    rancher2_bootstrap.admin will be updated in-place
> 
> And I did not change anything on the UI

Not clear the 2 points you are mentioning:
1. Is it getting Unauthorized errors when applying or is it solved applying again??  is this happening first tf run, all tf run or when?? Could you please explain a little bit more??
2. What is the config skew?? What is the argument trying to be updated, `current_password`?? If it's just `current_password` to be updated, you could try removing it from the bootstrap resource once applies  or set it equal as `password` value.

**Comment by jjhidalgar** [comment]
Sorry for not explaining with more detail.

For 1), I can not replicate it right now, I will share more info if I see it again. But basically, it showed a "Unauthorized" error when terraform was refreshing the state, but not always, only sometimes.

For 2) This is the issue:

```
Terraform will perform the following actions:

  # rancher2_bootstrap.admin will be updated in-place
  ~ resource "rancher2_bootstrap" "admin" {
      ~ current_password   = (sensitive value)
        id                 = "user-9cjr2"
        # (9 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

And if I apply, and then run terraform plan/apply again, same thing. In other words, it always has a change to "apply", and I'm not making any password change.

I fixed it with:

```
  lifecycle {
    ignore_changes = [
      current_password,
    ]
  }
```

But maybe this is just how it is supposed to be.

**Comment by rawmind0** [comment]
Yeah, `current_password` should just be used for recovering bootstrap. To avoid diffs once bootstrap works, you could ignore changes as you did or you could try removing it from the bootstrap resource.

**Comment by pulkit-servian** [comment]
> You may have another option here, setting `--set bootstrapPassword=ANY_PASSWORD` and then configure the `rancher2_bootstrap.current_password=ANY_PASSWORD`, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap#current_password

I had tried this as well as solution provided by @mitchellmaler. But still the same unauthorised error. Any latest fix for this?

Below terraform debug for reference:

[WARN]  Provider "registry.terraform.io/rancher/rancher2" produced an invalid plan for rancher2_bootstrap.admin, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .telemetry: planned value cty.False for a non-computed attribute
      - .token_update: planned value cty.False for a non-computed attribute
      - .ui_default_landing: planned value cty.StringVal("ember") for a non-computed attribute
      - .token_ttl: planned value cty.NumberIntVal(0) for a non-computed attribute
